[project]
name = "grades-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dataclasses-json>=0.6.7",
    "flask>=3.1.0",
    "flask-tailwind>=0.2.2",
    "prettytable>=3.16.0",
]
